# SPDX-License-Identifier: MIT
name: Resource Scheduler
version: v0.8.14
category: System
description: Schedule native workloads from control-plane events and current Metadata state.
projectURL: https://github.com/PastureStack/resource-scheduler
labels:
  io.rancher.orchestration.supported: 'cattle'
