# SPDX-License-Identifier: MIT
version: '2'
services:
  healthcheck:
    image: ghcr.io/pasturestack/metadata-healthcheck:v0.3.14@sha256:00d2e0a6c547d7f0e2e7344c19483e7459a2e75fd2062a19b5abfa92df0c9bce
    restart: always
    environment:
      PLATFORM_CA_ROOT: /var/lib/rancher/etc/ssl/ca.crt
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
