# SPDX-License-Identifier: MIT
.catalog:
  name: PastureStack Network Policy Manager
  version: v0.3.3
  description: Enforce metadata-defined network policy on every managed host with independently owned nftables rules.
  minimum_rancher_version: v1.6.26-rc1

network-policy-manager:
  start_on_create: true
