[tox]
envlist=flake8, py314

[testenv]
package=skip
install_command=python -I -m pip install --no-index --find-links=/opt/catalog-service-wheelhouse {opts} {packages}
deps=-rrequirements.lock
changedir=core
pass_env=
    CATALOG_SERVICE_BIN
    CATALOG_TEST_BRANCH
    CATALOG_TEST_BASE_URL
    CATALOG_TEST_COMMIT
    CATALOG_TEST_NAME
    CATALOG_TEST_REPO
commands=pytest -q {posargs}

[testenv:flake8]
deps=-rrequirements.lock
changedir={toxinidir}
commands=flake8 core
