# SPDX-License-Identifier: MIT
version: '2'
services:
  nfs-storage-driver:
    image: ghcr.io/pasturestack/nfs-storage-driver:v0.9.13
    privileged: true
    network_mode: host
    environment:
      NFS_SERVER: '${NFS_SERVER}'
      MOUNT_DIR: '${MOUNT_DIR}'
      MOUNT_OPTS: '${MOUNT_OPTS},${NFS_VERS}'
      ON_REMOVE: '${ON_REMOVE}'
      PASTURESTACK_DEBUG: '${PASTURESTACK_DEBUG}'
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
      io.rancher.container.dns: 'true'
    volumes:
    - /run:/run
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
